import ProjectForm from '@/components/ui/projectForm';
import React from 'react';
export const metadata = {
    title: "Project",
    description: "Generated by Milon Hossain",
}
const ProjectPage = () => {
    return (
        <div className='bg-white'>
           <ProjectForm/>
        </div>
    );
};

export default ProjectPage;