import ContactPage from "@/components/Contact/ContactPage";
export const metadata = {
    title: "Contact Me",
    description: "Generated by Milon Hossain",
}
const page = () => {
    return (
        <div className="min-h-screen">
            <ContactPage/>
        </div>
    );
};

export default page;