import ProjectDetailsCard from "@/components/ui/ProjectDetailsCard";
export const metadata = {
    title: "Project Details",
    description: "Generated by Milon Hossain",
}
const singleProject =async ({params}:{params:Promise<{projectId:string}>}) => {
    const {projectId} = await params
    const res=await fetch(`${process.env.SERVER_URL}/api/project/${projectId}`,{cache:'no-store'})
    const project=await res.json()
    return (
        <div className='min-h-screen'>
            <ProjectDetailsCard project={project.data}/>
        </div>
    );
};

export default singleProject;