import BlogDetailsCard from "@/components/ui/BlogDetailsCard";
export const metadata = {
    title: "Blog Details",
    description: "Generated by Milon Hossain",
}
const BlogsSingle = async ({params}:{params:Promise<{blogId:string}>}) => {
    const {blogId} = await params
    const res=await fetch(`${process.env.SERVER_URL}/api/blog/${blogId}`,{cache:'no-store'})
    const blog=await res.json()
    return (
        <div>
            <BlogDetailsCard blog={blog.data}/>
        </div>
    );
};

export default BlogsSingle;