'use server'
import ProfilePage from "@/components/Profile/ProfilePage";
import { getServerSession } from "next-auth";
// export const metadata = {
//     title: "Dashboard",
//     description: "Generated by Milon Hossain",
// }
const Page = async () => {
    const session = await getServerSession();

    return (
        <div className="bg-white min-h-screen">
            <ProfilePage session={session} />
        </div>
    );
};

export default Page;
