
import BlogForm from "@/components/ui/blogForm";
export const metadata = {
    title: "Post Blog",
    description: "Generated by Milon Hossain",
}

const page = () => {
    return (
        <div className="">
            <BlogForm/>
        </div>
    );
};

export default page;